# Generated by Django 2.2.6 on 2019-10-20 13:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='class_no',
            field=models.IntegerField(choices=[(1, 'A10-1A'), (2, 'A10-1B'), (3, 'A10-1C'), (4, 'A10-1D'), (5, 'A13-3A'), (6, 'A1-NKN')]),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0, 3600), validators=[django.core.validators.MinValueValidator(datetime.timedelta(0, 3600))]),
        ),
    ]
