# Generated by Django 2.2.6 on 2019-11-04 07:42

import datetime
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 7, 42, 35, 62321, tzinfo=utc)),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'lecture')},
        ),
    ]
