# Generated by Django 2.2.6 on 2019-10-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20191020_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='class_no',
            new_name='Class',
        ),
    ]
