# Generated by Django 2.2.6 on 2019-10-20 14:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_auto_20191020_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 14, 4, 27, 318627, tzinfo=utc)),
        ),
    ]
