# Generated by Django 2.2.6 on 2019-10-20 15:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_auto_20191020_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 20, 15, 48, 36, 964610, tzinfo=utc)),
        ),
    ]
