# Generated by Django 2.2.6 on 2019-11-04 06:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_auto_20191104_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecture',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 6, 1, 57, 182506, tzinfo=utc)),
        ),
    ]
